### PR TITLE
Update validates_timeliness gem to work with Ruby 3

### PR DESCRIPTION
**Pull request by Yannickdonners**
The current version of `validates_timeliness` is locked to `~> 4.1`. 
With changes to splat operators in Ruby 3 that version is no longer compatible with Ruby 3.
Hence, we need to upgrade to `6.0.0.beta2`. The tag creation and naming of that gem is a mystery to me, but from what I gather, this should be a stable (enough) version.

### CODE REVIEW

**Review by domininik — COMMENTED** [review]
And how about not requiring any specific version?

**Comment by Yannickdonners** [comment]
Because it then resolves to `5.0.0`. That was released in April 2021 and not yet incorporates the relevant fixes.

**Review by domininik — APPROVED** [review]

**Comment by Yannickdonners** [comment]
I'm not authorised to merged this, can you Dominik? :)

**Comment by domininik** [comment]
released https://rubygems.org/gems/railjet/versions/3.4.0

**Pull request merged**
