### PR TITLE
Fix merging ActiveModel::Errors

### PR DESCRIPTION
**Pull request by domininik**
I noticed 
```
FrozenError:
 can't modify frozen Hash
```
while upgrading to Rails `6.1`

Since Rails `5.2` it should be possible to just merge errors without a workarounds.

Tested with Rails `4.2`, `5.0`, `5.1`, `5.2`, `6.0`, `6.1`, `6.2`.

### CODE REVIEW

**Comment by domininik** [comment]
Hm, Semaphore needs some configuration update.

**Review by stephan-roolvink — APPROVED** [review]

**Comment by domininik** [comment]
@stephan-roolvink I'm missing some access rights. 
Can you please disconnect Semaphore in repo settings?
And/or you can give the SRE Team full admin rights if you think it's fine.

**Comment by stephan-roolvink** [comment]
> @stephan-roolvink I'm missing some access rights.
> Can you please disconnect Semaphore in repo settings?
> And/or you can give the SRE Team full admin rights if you think it's fine.

You should have access now, and Semaphore has been removed.

**Comment by domininik** [comment]
Awesome, thanks!

**Comment by domininik** [comment]
releases as `3.3.0`

**Pull request merged**
